# The code assumes that this table exists, so don't delete it even if you remove
# all aliases from here.
[aliases]
# The aliases here should be kept in sync with the `[default alias: blah]` notes
# in the first line of the relevant commands' help text.
b = ["bookmark"]
ci = ["commit"]
desc = ["describe"]
st = ["status"]

[diff.color-words]
conflict = "materialize"
max-inline-alternation = 3
context = 3

[diff.git]
context = 3

[experimental-advance-branches]
enabled-branches = []
disabled-branches = []

[git]
colocate = true
private-commits = "none()"
push-new-bookmarks = false
sign-on-push = false
track-default-bookmark-on-clone = true

[ui]
always-allow-large-revsets = true
color = "auto"
diff-formatter = ":color-words"
diff-instructions = true
graph.style = "curved"
pager = { command = ["less", "-FRX"], env = { LESSCHARSET = "utf-8" } }
paginate = "auto"
progress-indicator = true
quiet = false
log-word-wrap = false
log-synthetic-elided-nodes = true
conflict-marker-style = "diff"
# signature verification is slow, disable by default
show-cryptographic-signatures = false
bookmark-list-sort-keys = ["name"]
# TODO: delete revsets-use-glob-by-default in jj 0.43+
revsets-use-glob-by-default = true

[ui.movement]
edit = false

[ui.streampager]
interface = "quit-if-one-page"
wrapping = "anywhere"
show-ruler = true

[snapshot]
max-new-file-size = "1MiB"
auto-track = "all()"
auto-update-stale = false

# TODO: https://github.com/jj-vcs/jj/issues/3419 - Remove when fully deprecated.
# The behavior when this flag is set to false is experimental and may be changed
# in the future.
[split]
legacy-bookmark-behavior = true
